!obj:pylearn2.models.mlp.MLP {
    batch_size: 128,
    layers: [
             !obj:pylearn2.models.maxout.MaxoutConvC01B {
                 layer_name: 'h0',
                 pad: 0,
                 tied_b: 1,
                 W_lr_scale: .05,
                 b_lr_scale: .05,
                 num_channels: 16,
                 num_pieces: 2,
                 kernel_shape: [8, 8],
                 pool_shape: [4, 4],
                 pool_stride: [4, 4],
                 irange: .005,
                 max_kernel_norm: .9,
                 partial_sum: 33,
             },
             !obj:pylearn2.models.maxout.MaxoutConvC01B {
                 layer_name: 'h1',
                 pad: 0,
                 tied_b: 1,
                 W_lr_scale: .05,
                 b_lr_scale: .05,
                 num_channels: 32,
                 num_pieces: 2,
                 kernel_shape: [4, 4],
                 pool_shape: [4, 4],
                 pool_stride: [2, 2],
                 irange: .005,
                 max_kernel_norm: 1.9365,
                 partial_sum: 15,
             },
             !obj:pylearn2.models.mlp.RectifiedLinear {
                 max_col_norm: 1.9365,
                 layer_name: 'h2',
                 dim: 256,
                 sparse_init: 15,
             },
             !obj:pylearn2.models.mlp.Linear {
                 max_col_norm: 1.9365,
                 layer_name: 'y',
                 dim: 18,
                 irange: .005
             }
            ],
    input_space: !obj:pylearn2.space.Conv2DSpace {
        shape: &window_shape [84, 84],
        num_channels: 4,
        axes: ['c', 0, 1, 'b'],
    }
}